### ISSUE TITLE
java.lang.NoClassDefFoundError: Failed resolution of: Lkotlin/jvm/internal/Lambda;

### ISSUE THREAD

**Issue by skfly007** [YvesCheung/UInspector#1]
when i use  uinspector in a android(java) project . 
config the build.gradle  file like this :
` debugImplementation('com.huya.mobile:Uinspector:1.0.10') `
it work well.

but when i  copy the *.arr file into the local and config the  build.gradle  file like this :
![image](https://user-images.githubusercontent.com/12248308/105575992-beb09880-5daa-11eb-81ca-8542348a48fd.png)
it report an error ?  Failed resolution of: Lkotlin/jvm/internal/Lambda;
i look for a long time , but can not find where is wrong ? can u help me?

**Comment by YvesCheung** [comment]
aar依赖会丢失所有间接依赖。
正确的依赖方式有三种：
1.按文档的方法添加jcenter远程依赖(最简单)
2.不要构建aar，而是publishMaven打包成一个本地maven库格式的文件夹，然后依赖这个文件夹，相当于aar+pom声明，利用maven pom.xml来下载间接依赖
3.如果一定要用aar，要把所有间接依赖补上。把我项目里dependencies的声明也搬到你的dependencies声明里

**Comment by skfly007** [comment]
好的，我明白了。谢谢！
