### ISSUE TITLE
应用反而变得流畅了?

### ISSUE THREAD

**Issue by liuhuan0225** [YvesCheung/UInspector#10]
你好 我使用了该库 用来调试项目  但是 我发现 当我在线上  移除该库时  反而 应用会变得卡顿 (一款直播项目 卡顿由头像框动画 能肉眼看出)
我找了许久才定位到该库   加上Uinspector 不卡顿,移除卡顿  ,目前绝对是这样的 没办法 我现在是这样使用的
 debugImplementation("io.github.yvescheung:Uinspector-optional-glide:2.0.19")
 releaseImplementation("io.github.yvescheung:Uinspector:2.0.19") {
        //在应用启动时， UInspector 会自动显示到通知栏上。你可以选择禁用这个特性
        exclude module: 'Uinspector-optional-autoinstall'
  }

请问  我为什么会这样  库里 有什么优化形的代码吗  (上面说的卡顿 不仅限于gif图片  还有 列表滑动 整个app都会有这种表现)

**Comment by YvesCheung** [comment]
考虑下是不是有基础库被升级了，比如appcompat这种库。对比下加了Uinspector和没加的dependencies，看是不是间接升级了库导致

**Comment by liuhuan0225** [comment]
感谢解答 已经找到问题了 是androidx.constraintlayout:constraintlayout的bug  我用的是2.0.1版本
万分感谢  困惑我许久
