### ISSUE TITLE
大佬 里面有库拉不下来砸办

### ISSUE THREAD

**Issue by OvenCroc** [YvesCheung/UInspector#9]
com.github.lzyzsd.randomcolor:library:1.0.0 这个库拉不下来, 是不是之前放jcenter上的

**Comment by YvesCheung** [comment]
这是个第三方库 我看看是不是改个依赖方式

**Comment by YvesCheung** [comment]
2.0.19 
com.github.lzyzsd.randomcolor:library:1.0.0 改为源码依赖

**Comment by OvenCroc** [comment]
好哒大佬, 效率杠杠的
